# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d5fa74a0cd19957de4bd66227a19d0d"
name = "admin-agent"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_draft_orders,read_customers,read_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
